### ISSUE TITLE
Cannot install torch 1.7.1 with cuda 11.1

### ISSUE THREAD

**Issue by vinit13792** [pieterblok/maskal#1]
When I tried following installation instructions in section 2.4, when i run `pip install -U torch==1.7.1 torchvision==0.8.2 -f https://download.pytorch.org/whl/cu111/torch_stable.html` it installs cuda 10.2 by default.

**Comment by pieterblok** [comment]
> When I tried following installation instructions in section 2.4, when i run `pip install -U torch==1.7.1 torchvision==0.8.2 -f https://download.pytorch.org/whl/cu111/torch_stable.html` it installs cuda 10.2 by default.

Is CUDA 10.2 your default version on your computer? Quite honestly, the CUDA version does not really matter, as long as detectron2 builds from source and you can access your GPU as computing device in your virtual environment. See steps 2.6 and 2.7 in the installation instruction.

**Comment by vinit13792** [comment]
My cuda version is 11.1 by default. And it started training!. Thank you for your hardwork. This software is really amazing!

**Comment by pieterblok** [comment]
> My cuda version is 11.1 by default. And it started training!. Thank you for your hardwork. This software is really amazing!

Perfect! And thank you for your kind words, I'm happy that this software can be of use for other people.
