### ISSUE TITLE
How to specify network_configs for ResNet-18?

### ISSUE THREAD

**Issue by adalinadalin** [pieterblok/maskal#10]
In the maskal/configs/COCO-InstanceSegmentation folder, there are many network settings, how to set the yaml file for ResNet-18?
For example how to change the mask_rcnn_R_50_FPN_3x.yaml setting to mask_rcnn_R_18_FPN.yaml?

**Comment by pieterblok** [comment]
> In the maskal/configs/COCO-InstanceSegmentation folder, there are many network settings, how to set the yaml file for ResNet-18?
> 
> For example how to change the mask_rcnn_R_50_FPN_3x.yaml setting to mask_rcnn_R_18_FPN.yaml?

@adalinadalin I have checked the configs folder, but there is no Resnet-18 config file (yet). The current configs folder is directly forked from Detectron2. 

I guess if you want to use Resnet-18, you can make your own yaml file with Depth: 18 under Model-Resnets. If it works out of the box, then that would create a Resnet-18 model. One problem might be the lack of pretrained weights. I haven't checked this though.

**Comment by pieterblok** [comment]
@adalinadalin Did you solve this? Shall I close this issue?

**Comment by adalinadalin** [comment]
@pieterblok Thanks for your reply. Yes, I can make my own yaml file with Depth: 18 under Model-Resnets. Detectron2 does not  provide a pretrain weights for ResNet-18 now.  You can close this issue. Thank you.
