### ISSUE TITLE
Detectron2 build/installation query

### ISSUE THREAD

**Issue by nick0tine** [pieterblok/maskal#14]
I am using detectron2 in my env already, so instead of building detectron2 like mentioned in the installation guidelines; I tried to use to pip installed version which was there in my env.

- The above steps caused me error where for fast_rcnn_inference() it says instead of 6 arguments 7 are passed.

So, my question: 
- Is it required to build the detectron2, can't I use the installed package of same cuda configuration?

- Is there any changes in maskal/detectron2 than that of detectron2 (as seems to be the case for some functions) and that's why re-building is required, is there any work-around to use the existing detectron2 package instead of rebuild?

**Comment by pieterblok** [comment]
@nick0tine Indeed, logic question. There are so many things changed (for example adding dropout layers for the Monte-Carlo dropout) that you've to build it again. Also, the approach is different: standard D2 is trained once, MaskAL is trained iteratively after every sampling and annotation. So I recommend to follow the steps and rebuild the code. Then it should work out of the box

**Comment by nick0tine** [comment]
Thanks for the quick explanation
